export const actions = {
  SET_PLAYERS: "SET_PLAYERS",
  SET_CURRENT_PLAYER: "SET_CURRENT_PLAYER",
  SET_CURRENT_PLAYER_PIC: "SET_CURRENT_PLAYER_PIC",
  SET_CURRENT_PLAYER_STATS: "SET_CURRENT_PLAYER_STATS",
  SET_LOADING: "SET_LOADING",
};
